server:
  port: 8080
  servlet:
      context-path: /ruleengine
logging:
  level:
    com.justworld: trace
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  kafka:
    consumer:
      enable-auto-commit: true
      group-id: ruleeinge
      auto-offset-reset: latest
      bootstrap-servers: 192.168.40.128:9092
    producer:
      bootstrap-servers: 192.168.40.128:9092
  datasource:
    name: custget
    type: com.alibaba.druid.pool.DruidDataSource #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://192.168.40.128:3306/custget?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: abc123
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      ## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:MYBATIS/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.justworld.custget.ruleengine.service.bo  # 注意：对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true

short-url-server:
  sina:
    url: https://api.weibo.com/2/short_url/shorten.json
    app_key: 3945911857
    app_secret: 114dfb7de4175000b432ff0676222062
    redirect_url: http://115.28.235.146:6010/fantds/
    token: 2.00z3GCYBdvdC_E514f2c1be10L8mHf
    code_url: https://api.weibo.com/oauth2/authorize?client_id=3945911857&response_type=code&redirect_uri=http://115.28.235.146:6010/fantds/
    auth_token_url: https://api.weibo.com/oauth2/access_token?client_id=3945911857&client_secret=114dfb7de4175000b432ff0676222062&grant_type=authorization_code&redirect_uri=http://115.28.235.146:6010/fantds/&code=b3c95e9c776bcaa5b41790aeff295daf

phone-identify-server:
  baidu:
    url: http://mobsec-dianhua.baidu.com/dianhua_api/open/location?tel=17001111234

  juhe:
    url: http://apis.juhe.cn/mobile/get?phone=13429667914&key=您申请的KEY


