logging:
  pattern:
    console: "%t %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %class{36}.%M %L - %msg%xEx%n"
  level:
    com.justworld: trace
#    org.springframework.security: trace
  file: /var/log/runningtrace.log
spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      auto.offset.reset: latest
  datasource:
    name: custget
    druid:
      #基本属性
      url: jdbc:mysql://mysql:3306/custget?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: Abcjust_world
      #配置初始化大小/最小/最大
      initial-size: 50
      min-idle: 50
      max-active: 100

#后台登录token设置
jwt_token:
  secret: justworld!QAZ
  expire_second: 604800
  remember_me_expire_second: 604800
