short-url-server:
  sina:
    url: https://api.weibo.com/2/short_url/shorten.json
    app_key: 3945911857
    app_secret: 114dfb7de4175000b432ff0676222062
    redirect_url: http://115.28.235.146:6010/fantds/
    token: 2.00z3GCYBdvdC_E514f2c1be10L8mHf
    code_url: https://api.weibo.com/oauth2/authorize?client_id=3945911857&response_type=code&redirect_uri=http://115.28.235.146:6010/fantds/
    auth_token_url: https://api.weibo.com/oauth2/access_token?client_id=3945911857&client_secret=114dfb7de4175000b432ff0676222062&grant_type=authorization_code&redirect_uri=http://115.28.235.146:6010/fantds/&code=b3c95e9c776bcaa5b41790aeff295daf
