logging:
  pattern:
    console: "%t %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %class{36}.%M %L - %msg%xEx%n"
  level:
    com.justworld: trace
spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.40.128:9092
    producer:
      bootstrap-servers: 192.168.40.128:9092
  datasource:
    name: custget
    druid:
      #基本属性
      url: jdbc:mysql://192.168.40.128:3306/custget?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: abc123
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20

