#外部短链服务接口
short-url-server:
  sina:
    url: https://api.weibo.com/2/short_url/shorten.json
    code_url: https://api.weibo.com/oauth2/authorize?client_id=${short-url-server.sina.app_key}&response_type=code&redirect_uri=${short-url-server.sina.redirect_url}
    auth_token_url: https://api.weibo.com/oauth2/access_token

#手机号码识别接口
phone-identify-server:
  baidu:
    url: http://mobsec-dianhua.baidu.com/dianhua_api/open/location?tel={1}

  juhe:
    key: 123456
    url: http://apis.juhe.cn/mobile/get?key=${phone-identify-server.juhe.key}&phone=
