logging:
  pattern:
    console: "%t %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %class{36}.%M %L - %msg%xEx%n"
  level:
    com.justworld: trace
    root: warn
    org.apache.ibatis.logging: info
    com.justworld.custget.ruleengine.dao: info
#    org.springframework.security: trace
#    org.springframework.kafka: info
#    org.apache.kafka: info

spring:
  kafka:
    bootstrap-servers: 192.168.40.128:9092
    consumer:
        auto-offset-reset: latest
  datasource:
    name: custget
    druid:
      #基本属性
      url: jdbc:mysql://192.168.40.128:3306/custget?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password:
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20

#后台登录token设置
jwt_token:
  secret: 123456
  expire_second: 1800
  remember_me_expire_second: 604800