version: '3.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper ## 镜像
    container_name: zookeeper
    ports:
      - "2181:2181" ## 对外暴露的端口号
  kafka:
    image: wurstmeister/kafka ## 镜像
    container_name: kafka
    volumes:
      - /etc/localtime:/etc/localtime ## 挂载位置（kafka镜像和宿主机器之间时间保持一直）
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/services/kafka-config/server.properties:/opt/kafka/config/server.properties
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.40.128 ## 修改:宿主机IP
#      KAFKA_LISTENERS: PLAINTEXT://:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.40.128:9092 ## 修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 ## 卡夫卡运行是基于zookeeper的
    depends_on:
      - zookeeper
  kafka-manager:
    image: sheepkiller/kafka-manager ## 镜像：开源的web管理kafka集群的界面
    container_name: kafka-manager
    environment:
      ZK_HOSTS: zookeeper:2181 ## 修改:宿主机IP
    ports:
      - "9000:9000" ## 暴露端口
    volumes:
      - /home/services/kafka-manager-config: /kafka-manager-1.3.1.8/conf

    depends_on:
      - zookeeper
      - kafka
